"""Channel groups

Revision ID: 6136bdc12bcf
Revises: d03dedaa0ca0
Create Date: 2024-07-29 19:10:06.707852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6136bdc12bcf'
down_revision: Union[str, None] = 'd03dedaa0ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_channel_groups',
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('channel_group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['channel_group_id'], ['channel_groups.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('channel_id', 'channel_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_channel_groups')
    op.drop_table('channel_groups')
    # ### end Alembic commands ###
